//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_APB
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public account()
        {
            this.billings = new HashSet<billing>();
            this.invoices = new HashSet<invoice>();
        }
    
        public int account_id { get; set; }
        public int cust_id { get; set; }
        public string account_no { get; set; }
        public int electricity_board_id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
        public string rr_number { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual electricity_board electricity_board { get; set; }
        public virtual ICollection<billing> billings { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
