//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_APB
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.accounts = new HashSet<account>();
            this.billings = new HashSet<billing>();
            this.feedbacks = new HashSet<feedback>();
        }
    
        public int cust_id { get; set; }
        public string cust_name { get; set; }
        public string account_type { get; set; }
        public string adress { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string email_id { get; set; }
        public string passsword { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<billing> billings { get; set; }
        public virtual ICollection<feedback> feedbacks { get; set; }
    }
}
