//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_APB
{
    using System;
    using System.Collections.Generic;
    
    public partial class electricity_board
    {
        public electricity_board()
        {
            this.accounts = new HashSet<account>();
            this.invoices = new HashSet<invoice>();
        }
    
        public int electricity_board_id { get; set; }
        public string electricity_board1 { get; set; }
        public string logo { get; set; }
        public string note { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<account> accounts { get; set; }
        public virtual ICollection<invoice> invoices { get; set; }
    }
}
