//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proiect_APB
{
    using System;
    using System.Collections.Generic;
    
    public partial class invoice
    {
        public int invoice_id { get; set; }
        public int electricity_board_id { get; set; }
        public int account_id { get; set; }
        public int tariff_id { get; set; }
        public Nullable<System.DateTime> readingdate { get; set; }
        public string bil_no { get; set; }
        public Nullable<double> present_reading { get; set; }
        public Nullable<double> previous_reading { get; set; }
        public Nullable<double> consumption_unit { get; set; }
        public Nullable<double> fixed_charge { get; set; }
        public Nullable<double> energy_charge { get; set; }
        public Nullable<double> tax { get; set; }
        public Nullable<double> bill_amount { get; set; }
        public Nullable<double> interest { get; set; }
        public Nullable<double> previous_balance { get; set; }
        public Nullable<double> others { get; set; }
        public Nullable<double> credit { get; set; }
        public Nullable<double> consession { get; set; }
        public Nullable<double> net_amount { get; set; }
        public Nullable<System.DateTime> due_date { get; set; }
        public string status { get; set; }
    
        public virtual account account { get; set; }
        public virtual electricity_board electricity_board { get; set; }
        public virtual tariff tariff { get; set; }
    }
}
